apiVersion: v1
kind: Service
metadata:
  name: intnet-grid-topology
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
  selector:
    app: intnet-grid-topology