replicaCount: 1
image:
  repository: intnet-grid-topology
  tag: latest
  pullPolicy: IfNotPresent
springProfile: "docker-dev"
service:
  type: ClusterIP
  port: 81
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi