replicaCount: 1
image:
  repository: confluentinc/cp-zookeeper
  tag: 7.3.1
service:
  type: ClusterIP
  port: 2181
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
pvc:
  storage:
    size: 1Gi