replicaCount: 1
image:
  repository: confluentinc/cp-zookeeper
  tag: 7.3.1
zookeeper:
  serverID: 1
  clientPort: 2181
  tickTime: 2000
  initLimit: 10
  syncLimit: 5
service:
  type: ClusterIP
  port: 2181
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
pvc:
  storage:
    size: 1Gi