apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-intnet-tenant
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: intnet-tenant
  template:
    metadata:
      labels:
        app: intnet-tenant
    spec:
      containers:
        - name: intnet-tenant
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfile }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}