apiVersion: apps/v1
kind: Deployment
metadata:
  name: intnet-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intnet-gateway
  template:
    metadata:
      labels:
        app: intnet-gateway
    spec:
      containers:
        - name: intnet-gateway
          image: intnet-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080