apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-timescale-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..labels" . | nindent 8 }}
    spec:
      containers:
        - name: timescale-db
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.security.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.security.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: timescale-db-pv
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: timescale-db-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-timescale-db-pvc