replicaCount: 1
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 8.11.1
service:
  type: ClusterIP
  port1: 9200
  port2: 9300
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 4Gi
pvc:
  storage:
    size: 8Gi