replicaCount: 1
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 8.11.1
service:
  type: ClusterIP
  port1: 9200
  port2: 9300
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
pvc:
  storage:
    size: 1Gi