-- V202502171122__Create_buses_table.sql
CREATE TABLE buses (
    id SERIAL PRIMARY KEY,
    grid_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,

    FOREIGN KEY (grid_id) REFERENCES grids(id)
);