replicaCount: 1
image:
  repository: modbus-adapter
  tag: latest
  pullPolicy: IfNotPresent
springProfile: "docker-dev"
service:
  type: ClusterIP
  port: 8080
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi