apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intnet-admin-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: intnet-admin-role
  apiGroup: rbac.authorization.k8s.io