replicaCount: 1
image:
  repository: confluentinc/cp-kafka
  tag: 7.3.1
service:
  type: ClusterIP
  port: 9092
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
pvc:
  storage:
    size: 1Gi
kafka:
  offsetsTopicReplicationFactor: "1"