apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelines-edit
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - experiments
  - runs
  - recurringruns
  - pipelines
  - scheduledworkflows
  - viewers
  verbs:
  - create
  - get
  - list
  - update
  - delete