apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-intnet-ml-admin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: intnet-ml-admin
      app.kubernetes.io/instance: std-release
      app: intnet-ml-admin
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: intnet-ml-admin
        app.kubernetes.io/name: intnet-ml-admin
        app.kubernetes.io/instance: std-release
    spec:
      serviceAccountName: intnet-ml-admin-sa
      containers:
        - name: intnet-ml-admin
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}