apiVersion: security.istio.io/v1beta1
kind: ServiceRole
metadata:
  name: ml-pipeline-access-role
  namespace: kubeflow
spec:
  rules:
  - services: ["ml-pipeline.kubeflow.svc.cluster.local"]
    methods: ["*"]
    paths: ["*"]