replicaCount: 1
image:
  repository: intnet-grid-device-manager
  tag: latest
  pullPolicy: IfNotPresent
springProfile: "docker-dev"
service:
  type: ClusterIP
  port: 85
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi