replicaCount: 1
image:
  repository: intnet-ml-admin
  tag: 0.1.0
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi