apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logstash-config

data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    output {
      stdout { codec => rubydebug }
      elasticsearch {
        hosts => ["std-release-elasticsearch:9200"]
      }
    }