imagePullPolicy: IfNotPresent

intnet-gateway:
  replicaCount: 1
intnet-tenant:
  replicaCount: 1
intnet-grid-data:
  replicaCount: 1
intnet-grid-topology:
  replicaCount: 1
intnet-grid-history:
  replicaCount: 1

grafana:
  replicaCount: 1
keycloak:
  replicaCount: 1
neo4j:
  replicaCount: 1
timescale-db:
  replicaCount: 1