replicaCount: 1
image:
  repository: intnet-admin
  tag: latest
  pullPolicy: IfNotPresent
springProfile: "docker-dev"
service:
  type: ClusterIP
  port: 20
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
volume:
  hostPath: "" # To be set by the intnet_initialization.sh script
  mountPath: /intnet