replicaCount: 1
image:
  repository: cassandra
  tag: latest
security:
  neo4jUser: neo4j
  neo4jPassword: example-password
service:
  type: ClusterIP
  port: 9042
resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 3Gi
pvc:
  storage:
    size: 2Gi