replicaCount: 1
image:
  repository: docker.elastic.co/logstash/logstash
  tag: 8.17.2

service:
  type: ClusterIP
  port: 5044

resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi