apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-intnet-training-data-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: intnet-training-data-manager
      app.kubernetes.io/instance: std-release
      app: intnet-training-data-manager
  template:
    metadata:
      labels:
        app: intnet-training-data-manager
        app.kubernetes.io/name: intnet-training-data-manager
        app.kubernetes.io/instance: std-release
    spec:
      containers:
        - name: intnet-training-data-manager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}