apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zookeeper
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..labels" . | nindent 8 }}
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - containerPort: 2181
          - containerPort: 2888
          - containerPort: 3888
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "{{ .Values.zookeeper.serverID }}"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.zookeeper.clientPort }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "{{ .Values.zookeeper.tickTime }}"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "{{ .Values.zookeeper.initLimit }}"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "{{ .Values.zookeeper.syncLimit }}"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: zookeeper-pv
              mountPath: /data
      volumes:
        - name: zookeeper-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-zookeeper-pvc