replicaCount: 1
image:
  repository: intnet.azurecr.io/intnet-grid-data
  tag: latest
  pullPolicy: Always
springProfile: "docker-prod"
service:
  type: ClusterIP
  port: 82
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
imagePullSecrets:
  - name: acr-secret