server:
  port: 8080

spring:
  application:
    name: intnet-gateway

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        cloud:
          loadbalancer: DEBUG
          gateway: DEBUG
        data:
          redis: DEBUG
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"