server:
  port: 8080

spring:
  application:
    name: intnet-tenant
  main:
    web-application-type: reactive
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
      client:
        namespace: default
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false


app:
  environment: ${APP_ENV:dev}

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus,health,info'
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always