replicaCount: 1
image:
  repository: intnet-training-data-manager
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 100
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi