replicaCount: 1
image:
  repository: docker.elastic.co/kibana/kibana
  tag: 8.11.1
service:
  type: ClusterIP
  port: 5601
resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
pvc:
  storage:
    size: 1Gi