image:
  repository: intnet-grid-data
  tag: latest
  pullPolicy: IfNotPresent
springProfile: "docker-dev"
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
