apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-elasticsearch-config
data:
  elasticsearch.yml: |-
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    http.port: 9200
    xpack.security.enabled: false