apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: 9200
      protocol: TCP
      name: http
    - port: {{ .Values.service.port2 }}
      targetPort: 9300
      protocol: TCP
      name: transport
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
