replicaCount: 1
image:
  repository: docker.io/bitnami/mongodb
  tag: latest
service:
  type: ClusterIP
  port: 27017
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
pvc:
  storage:
    size: 2Gi