replicaCount: 1
image:
  repository: simulated-device-modbus
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5020
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi