apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..labels" . | nindent 8 }}
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - /opt/keycloak/bin/kc.sh
            - start-dev
            - --http-port=8080
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.security.keycloakUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.security.keycloakPassword }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: keycloak-pv
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-keycloak-pvc